name=MyLib
version=0.1.0
author=Maximiliano Ramirez <maximiliano.ramirezbravo@gmail.com>
maintainer=Maximiliano Ramirez <maximiliano.ramirezbravo@gmail.com>
sentence=Short description.
paragraph=Longer description of the library.
category=One of: Display, Communication, Signal Input/Output, Sensors, Device Control, Timing, Data Storage, Data Processing, Other
url=https://github.com/alkonosst/MyLib
architectures=*
includes=MyLib.h