# When a semantic version tag is pushed (e.g. v1.2.3): create the GitHub release and publish the
# package to the PlatformIO Registry.
# NOTE: no CI is run for release tags, so make sure to create a tag only after the CI has passed on the main branch.
name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: alkonosst/templates/.github/actions/release@v1

  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: alkonosst/templates/.github/actions/setup-python@v1
      - uses: alkonosst/templates/.github/actions/setup-pio@v1
      - uses: alkonosst/templates/.github/actions/pio-publish@v1
        with:
          auth-token: ${{ secrets.PLATFORMIO_AUTH_TOKEN }}
